// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gridfs.proto
#ifndef GRPC_gridfs_2eproto__INCLUDED
#define GRPC_gridfs_2eproto__INCLUDED

#include "gridfs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace gridfs {

// Servicio NameNode
class NameNode final {
 public:
  static constexpr char const* service_full_name() {
    return "gridfs.NameNode";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::gridfs::RegisterResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::RegisterResponse>> AsyncRegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::RegisterResponse>>(AsyncRegisterDataNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::RegisterResponse>> PrepareAsyncRegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::RegisterResponse>>(PrepareAsyncRegisterDataNodeRaw(context, request, cq));
    }
    virtual ::grpc::Status GetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::gridfs::GetPlanResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::GetPlanResponse>> AsyncGetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::GetPlanResponse>>(AsyncGetPlanRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::GetPlanResponse>> PrepareAsyncGetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::GetPlanResponse>>(PrepareAsyncGetPlanRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest* request, ::gridfs::RegisterResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest* request, ::gridfs::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest* request, ::gridfs::GetPlanResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest* request, ::gridfs::GetPlanResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::RegisterResponse>* AsyncRegisterDataNodeRaw(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::RegisterResponse>* PrepareAsyncRegisterDataNodeRaw(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::GetPlanResponse>* AsyncGetPlanRaw(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gridfs::GetPlanResponse>* PrepareAsyncGetPlanRaw(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::gridfs::RegisterResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gridfs::RegisterResponse>> AsyncRegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gridfs::RegisterResponse>>(AsyncRegisterDataNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gridfs::RegisterResponse>> PrepareAsyncRegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gridfs::RegisterResponse>>(PrepareAsyncRegisterDataNodeRaw(context, request, cq));
    }
    ::grpc::Status GetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::gridfs::GetPlanResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gridfs::GetPlanResponse>> AsyncGetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gridfs::GetPlanResponse>>(AsyncGetPlanRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gridfs::GetPlanResponse>> PrepareAsyncGetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gridfs::GetPlanResponse>>(PrepareAsyncGetPlanRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest* request, ::gridfs::RegisterResponse* response, std::function<void(::grpc::Status)>) override;
      void RegisterDataNode(::grpc::ClientContext* context, const ::gridfs::RegisterRequest* request, ::gridfs::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest* request, ::gridfs::GetPlanResponse* response, std::function<void(::grpc::Status)>) override;
      void GetPlan(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest* request, ::gridfs::GetPlanResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::gridfs::RegisterResponse>* AsyncRegisterDataNodeRaw(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gridfs::RegisterResponse>* PrepareAsyncRegisterDataNodeRaw(::grpc::ClientContext* context, const ::gridfs::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gridfs::GetPlanResponse>* AsyncGetPlanRaw(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gridfs::GetPlanResponse>* PrepareAsyncGetPlanRaw(::grpc::ClientContext* context, const ::gridfs::GetPlanRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterDataNode_;
    const ::grpc::internal::RpcMethod rpcmethod_GetPlan_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterDataNode(::grpc::ServerContext* context, const ::gridfs::RegisterRequest* request, ::gridfs::RegisterResponse* response);
    virtual ::grpc::Status GetPlan(::grpc::ServerContext* context, const ::gridfs::GetPlanRequest* request, ::gridfs::GetPlanResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterDataNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterDataNode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterDataNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterDataNode(::grpc::ServerContext* /*context*/, const ::gridfs::RegisterRequest* /*request*/, ::gridfs::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterDataNode(::grpc::ServerContext* context, ::gridfs::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::gridfs::RegisterResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPlan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPlan() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetPlan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlan(::grpc::ServerContext* /*context*/, const ::gridfs::GetPlanRequest* /*request*/, ::gridfs::GetPlanResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPlan(::grpc::ServerContext* context, ::gridfs::GetPlanRequest* request, ::grpc::ServerAsyncResponseWriter< ::gridfs::GetPlanResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterDataNode<WithAsyncMethod_GetPlan<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterDataNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterDataNode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::gridfs::RegisterRequest, ::gridfs::RegisterResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gridfs::RegisterRequest* request, ::gridfs::RegisterResponse* response) { return this->RegisterDataNode(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterDataNode(
        ::grpc::MessageAllocator< ::gridfs::RegisterRequest, ::gridfs::RegisterResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gridfs::RegisterRequest, ::gridfs::RegisterResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterDataNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterDataNode(::grpc::ServerContext* /*context*/, const ::gridfs::RegisterRequest* /*request*/, ::gridfs::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterDataNode(
      ::grpc::CallbackServerContext* /*context*/, const ::gridfs::RegisterRequest* /*request*/, ::gridfs::RegisterResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetPlan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPlan() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::gridfs::GetPlanRequest, ::gridfs::GetPlanResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gridfs::GetPlanRequest* request, ::gridfs::GetPlanResponse* response) { return this->GetPlan(context, request, response); }));}
    void SetMessageAllocatorFor_GetPlan(
        ::grpc::MessageAllocator< ::gridfs::GetPlanRequest, ::gridfs::GetPlanResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gridfs::GetPlanRequest, ::gridfs::GetPlanResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPlan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlan(::grpc::ServerContext* /*context*/, const ::gridfs::GetPlanRequest* /*request*/, ::gridfs::GetPlanResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPlan(
      ::grpc::CallbackServerContext* /*context*/, const ::gridfs::GetPlanRequest* /*request*/, ::gridfs::GetPlanResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterDataNode<WithCallbackMethod_GetPlan<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterDataNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterDataNode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterDataNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterDataNode(::grpc::ServerContext* /*context*/, const ::gridfs::RegisterRequest* /*request*/, ::gridfs::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPlan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPlan() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetPlan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlan(::grpc::ServerContext* /*context*/, const ::gridfs::GetPlanRequest* /*request*/, ::gridfs::GetPlanResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterDataNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterDataNode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterDataNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterDataNode(::grpc::ServerContext* /*context*/, const ::gridfs::RegisterRequest* /*request*/, ::gridfs::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterDataNode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPlan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPlan() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetPlan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlan(::grpc::ServerContext* /*context*/, const ::gridfs::GetPlanRequest* /*request*/, ::gridfs::GetPlanResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPlan(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterDataNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterDataNode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterDataNode(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterDataNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterDataNode(::grpc::ServerContext* /*context*/, const ::gridfs::RegisterRequest* /*request*/, ::gridfs::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterDataNode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPlan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPlan() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPlan(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPlan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlan(::grpc::ServerContext* /*context*/, const ::gridfs::GetPlanRequest* /*request*/, ::gridfs::GetPlanResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPlan(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterDataNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterDataNode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gridfs::RegisterRequest, ::gridfs::RegisterResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gridfs::RegisterRequest, ::gridfs::RegisterResponse>* streamer) {
                       return this->StreamedRegisterDataNode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterDataNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterDataNode(::grpc::ServerContext* /*context*/, const ::gridfs::RegisterRequest* /*request*/, ::gridfs::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterDataNode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gridfs::RegisterRequest,::gridfs::RegisterResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPlan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPlan() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gridfs::GetPlanRequest, ::gridfs::GetPlanResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gridfs::GetPlanRequest, ::gridfs::GetPlanResponse>* streamer) {
                       return this->StreamedGetPlan(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPlan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPlan(::grpc::ServerContext* /*context*/, const ::gridfs::GetPlanRequest* /*request*/, ::gridfs::GetPlanResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPlan(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gridfs::GetPlanRequest,::gridfs::GetPlanResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterDataNode<WithStreamedUnaryMethod_GetPlan<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterDataNode<WithStreamedUnaryMethod_GetPlan<Service > > StreamedService;
};

}  // namespace gridfs


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_gridfs_2eproto__INCLUDED
